name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: macos-11

    steps:
    - uses: actions/checkout@v2

    - name: Build and test CoreData framework
      run: xcodebuild clean build test -scheme "DGPKeyChainCI" -destination 'platform=macOS,arch=x86_64' ONLY_ACTIVATE_ARCH=NO CODE_SIGNING_REQUIRED=NO
